[tox]
envlist = ruff, py
isolated_build = True

[testenv:ruff]
skip_install = true
deps =
    ruff>=0.1.0
changedir = {toxinidir}
commands =
    ruff check .

[testenv:py]
commands =
    python -m hotglue_smoke_test.self_check
