name: Release to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          version: "0.11.31"
          python-version: "3.10"
          enable-cache: true

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
